# Generated by Django 5.2.12 on 2026-03-20 03:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='photo',
            field=models.FileField(blank=True, upload_to='lost-pets/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='last_seen_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
