# Generated by Django 5.2.12 on 2026-03-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_businessprofile_grace_expires_at_and_more'),
        ('lost_pets', '0003_lostpetreport_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='pet_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_pet_reports', to='accounts.petprofile'),
        ),
    ]
