export const PET_BREEDS_BY_TYPE: Record<string, string[]> = {
  dog: [
    "Mestizo",
    "Labrador Retriever",
    "Poodle",
    "French Bulldog",
    "Golden Retriever",
    "Yorkshire Terrier",
    "Beagle",
    "Dachshund",
    "Chihuahua",
    "Cocker Spaniel",
    "Border Collie",
    "Pug",
  ],
  cat: [
    "Mestizo",
    "Siamés",
    "Persa",
    "Maine Coon",
    "British Shorthair",
    "Bengalí",
    "Ragdoll",
    "Sphynx",
    "Azul Ruso",
    "Angora",
  ],
  other: ["Conejo", "Hámster", "Hurón", "Cobaya", "Ave", "Tortuga"],
};
