# Generated by Django 5.2.12 on 2026-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_operational_quality'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='places_plac_status_8eccee_idx',
            old_name='places_plac_status_33e508_idx',
        ),
        migrations.RenameIndex(
            model_name='place',
            new_name='places_plac_slug_1928e6_idx',
            old_name='places_plac_slug_9f756d_idx',
        ),
        migrations.RenameIndex(
            model_name='place',
            new_name='places_plac_region_75a749_idx',
            old_name='places_plac_region_a0bca2_idx',
        ),
    ]
