# Generated by Django 5.2.12 on 2026-03-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessprofile_place_petownerprofile_address_line_and_more'),
        ('places', '0003_rename_places_plac_status_33e508_idx_places_plac_status_8eccee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner_business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to='accounts.businessprofile'),
        ),
    ]
