# Generated by Django 5.2.12 on 2026-03-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform admin'), ('moderator', 'Moderator'), ('analyst', 'Analyst'), ('business_owner', 'Business owner'), ('pet_owner', 'Pet owner')], default='moderator', max_length=32),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=160)),
                ('business_kind', models.CharField(choices=[('veterinary', 'Veterinaria'), ('daycare', 'Guarderia'), ('emergency', 'Emergencia 24/7'), ('shelter', 'Refugio'), ('park', 'Parque')], max_length=20)),
                ('phone', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=120)),
                ('region', models.CharField(default='Región Metropolitana', max_length=120)),
                ('website', models.URLField(blank=True)),
                ('membership_status', models.CharField(choices=[('grace', 'Grace period'), ('active', 'Active membership'), ('past_due', 'Past due'), ('free_forever', 'Free forever')], default='grace', max_length=20)),
                ('grace_expires_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business profile',
                'verbose_name_plural': 'Business profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='PetOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=40)),
                ('commune', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(default='Región Metropolitana', max_length=120)),
                ('marketing_opt_in', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet owner profile',
                'verbose_name_plural': 'Pet owner profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.petownerprofile')),
            ],
            options={
                'verbose_name': 'Pet profile',
                'verbose_name_plural': 'Pet profiles',
                'ordering': ['name'],
            },
        ),
    ]
