# Generated by Django 5.2.12 on 2026-03-20 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active_and_more'),
        ('places', '0003_rename_places_plac_status_33e508_idx_places_plac_status_8eccee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to='places.place'),
        ),
        migrations.AddField(
            model_name='petownerprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
