# Generated by Django 5.2.12 on 2026-03-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessprofile_place_petownerprofile_address_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='grace_expires_at',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='membership_status',
        ),
    ]
