# Generated by Django 5.2.12 on 2026-03-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('audience', models.CharField(choices=[('business', 'Business'), ('pet_owner', 'Pet owner')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One time'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='CLP', max_length=8)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('max_places', models.PositiveIntegerField(default=1)),
                ('max_pets', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Membership plan',
                'verbose_name_plural': 'Membership plans',
                'ordering': ['audience', 'price_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_assignments', to='contenttypes.contenttype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Membership assignment',
                'verbose_name_plural': 'Membership assignments',
                'ordering': ['-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['owner_content_type', 'owner_object_id'], name='memberships_owner_c_adefc3_idx'), models.Index(fields=['status'], name='memberships_status_635dcf_idx')],
            },
        ),
    ]
