# Generated by Django 5.2.13 on 2026-04-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='placeviewevent',
            new_name='analytics_p_created_a23764_idx',
            old_name='analytics_p_created_f61f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='placeviewevent',
            new_name='analytics_p_place_i_3ed6bb_idx',
            old_name='analytics_p_place_i_0e1236_idx',
        ),
        migrations.RenameIndex(
            model_name='placeviewevent',
            new_name='analytics_p_device__4f2cc7_idx',
            old_name='analytics_p_device__a09959_idx',
        ),
        migrations.RenameIndex(
            model_name='placeviewevent',
            new_name='analytics_p_is_regi_0f219f_idx',
            old_name='analytics_p_is_regi_52af55_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='analytics_s_created_df2559_idx',
            old_name='analytics_s_created_6aaae7_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='analytics_s_categor_91cbcd_idx',
            old_name='analytics_s_categor_cfd2ab_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='analytics_s_device__9c452e_idx',
            old_name='analytics_s_device__e964da_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='analytics_s_is_regi_de8bac_idx',
            old_name='analytics_s_is_regi_117eef_idx',
        ),
    ]
